# Generated by Django 6.0.5 on 2026-05-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vinyl", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="description",
        ),
    ]
