# Generated by Django 6.0.5 on 2026-05-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vinyl", "0002_remove_album_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="image",
            field=models.ImageField(
                default="img/default-album.jpg", upload_to="albums/"
            ),
        ),
    ]
