# Generated by Django 6.0.5 on 2026-05-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vinyl", "0003_album_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="image",
        ),
        migrations.AddField(
            model_name="album",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="albums/"),
        ),
    ]
