# Generated by Django 6.0.5 on 2026-05-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vinyl", "0004_remove_album_image_album_cover"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ("username",)},
        ),
        migrations.AddField(
            model_name="user",
            name="favorite_artist",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="favorite_genres",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="collection",
            unique_together={("user", "album")},
        ),
    ]
