# Generated by Django 6.0.5 on 2026-05-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vinyl", "0005_alter_user_options_user_favorite_artist_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="favorite_artist",
            new_name="country",
        ),
        migrations.RemoveField(
            model_name="user",
            name="favorite_genres",
        ),
    ]
