# Generated by Django 6.0.5 on 2026-05-27 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vinyl", "0006_rename_favorite_artist_user_country_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artist",
            options={"ordering": ["name"]},
        ),
    ]
