# Generated by Django 6.0.5 on 2026-05-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vinyl", "0007_alter_artist_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="album",
            options={"ordering": ["-created_at"]},
        ),
    ]
