# Generated by Django 6.0.5 on 2026-05-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vinyl", "0008_alter_album_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="album",
            options={},
        ),
        migrations.AlterField(
            model_name="collection",
            name="status",
            field=models.CharField(
                choices=[
                    ("owned", "Owned"),
                    ("wishlist", "Wishlist"),
                    ("trade", "Trade"),
                ],
                default="owned",
                max_length=20,
            ),
        ),
    ]
